### ISSUE TITLE
Creating a worker on electron doesn't include Node.js

### ISSUE THREAD

**Issue by Fransebas** [GoogleChromeLabs/worker-plugin#53] opened 2020-02-08 20:00 UTC
Hi, amazing library.
I'm having problems because when I create a simple worker like this one:

```
// node.js library
var child_process = require('child_process');

console.log("This is a testing string");
```

If I create the worker like this:

`var worker1 = new Worker('./workerTest.js');`

It works, but when I create the worker like this:

`var worker2 = new Worker('./workerTest.js', { type: 'module' });`

It shows this message `Module not found: Error: Can't resolve 'child_process'` meaning that the `worker2` doesn't include `Node.js`. I don't know if I should include another option apart from `type: 'module' ` or if this is not supported by this library.

Also, I can't use `worker1` method because the real worker is more complex and has a lot of imports.

**Comment by Fransebas** [comment] 2020-02-08 20:01
I'm using `electron": "^8.0.0` and node version `v12.15.0`

**Comment by developit** [comment] 2020-02-21 02:15
Hiya - this module bundles Web Workers, not Node workers_threads. I think it might be possible to add an option for outputing worker_threads, but I worry that `{ type: 'module' }` is misleading for that use-case, since Node does not actually have any plans to support a "type" option that I'm aware of.

**Comment by developit** [comment] 2020-02-21 02:19
I'm actually going to close this issue since it's a duplicate of #10 - we can continue discussion there!

**Closed by developit** 2020-02-21 02:19 UTC
Labels: enhancement, needs more info

**Comment by 2xAA** [comment] 2020-12-23 13:11
Hey @developit - I'm also facing this issue.
The scenario isn't to use worker_threads, it's to use a Worker with a NodeJS context in Electron:
https://www.electronjs.org/docs/tutorial/multithreading#multi-threaded-nodejs

My use-case is to use OffscreenCanvas within a Worker, which is impossible in a worker_therad.

I'm trying to migrate from `worker-loader`, but facing the same `Module not found: Error: Can't resolve 'child_process'` as @Fransebas had back in Feb.

**Comment by edenhermelin** [comment] 2021-03-03 22:50
@2xAA did  did you manage to workaround this issue? Im facing it too..

**Comment by 2xAA** [comment] 2021-03-04 09:29
@edenhermelin Unfortunately not. I wrote some pretty awful `__dirname` hacks around a library we were consuming to make it work with `worker-loader`.

Worked for a while but has broken with Electron 11 for some reason.

**Comment by rathboma** [comment] 2021-06-01 21:24
I'm trying to solve this exact issue also.

@edenhermelin or @2xAA did either of you figure this out?

I also followed the directions in #75, which **DOES** let me create a worker from the `main` process, but not from the `renderer` process.

**Comment by rathboma** [comment] 2021-06-01 21:26
@developit can we re-open this issue? It is not the same as creating a node worker.

What this is about:
1. Creating a webworker
2. That references node.js APIs
3. That also references externalized native dependencies.

**Comment by 2xAA** [comment] 2021-09-20 16:09
> @edenhermelin or @2xAA did either of you figure this out?

Nope, sorry.
This was my awful workaround for the library I was consuming. Might be quite specific, however.

https://github.com/vcync/modV/commit/81eac0a13017f776af913449fad8c06a7c408821#diff-7b4e11be73603a3ee2c4d37bd49f053930d6056507a005e5639cea7c15686d5fR7-R14
